"use client";
import {useEffect,useMemo,useState} from "react";
type Contribution={id:string;type:string;sender_name:string;content:string;mood:string;created_at:string};
const gifts=[["🌷","flower","Send a flower","Choose a flower and leave it in the garden."],["🫂","hug","Send a hug","No words. Just a hug."],["💌","note","Leave a note","A tiny message, signed or anonymous."],["😂","joke","Make her laugh","Terrible jokes are strongly encouraged."],["☕","coffee","Send coffee","Emotionally responsible caffeine."],["🍫","chocolate","Send chocolate","A completely reasonable solution."],["🧸","teddy","Send a teddy","For maximum tiny comfort."],["✨","sparkle","Leave a sparkle","No reason. Best reason."],["🫶","highfive","High five","You made it through another day."],["🎵","song","Leave a song","Attach a song to a moment."],["🏔️","escape","Little escape","A tiny mountain-shaped break."]];
const labels:Record<string,string>={flower:"left a flower",hug:"sent a hug",note:"left a note",joke:"tried to make Noor laugh",coffee:"sent coffee",chocolate:"sent chocolate",teddy:"sent a teddy",sparkle:"left a sparkle",highfive:"sent a high five",song:"left a song",escape:"left a little escape"};
export default function NoorWorld(){
 const [tab,setTab]=useState<"home"|"play"|"send">("home"),[night,setNight]=useState(false),[feed,setFeed]=useState<Contribution[]>([]),[selected,setSelected]=useState<string[]|null>(null),[sender,setSender]=useState(""),[content,setContent]=useState(""),[mood,setMood]=useState("just-because"),[busy,setBusy]=useState(false),[toast,setToast]=useState("");
 const load=async()=>{const r=await fetch("/api/send",{cache:"no-store"});if(r.ok){const j=await r.json();setFeed(j.data||[])}};
 useEffect(()=>{load();const id=window.setInterval(load,15000);return()=>window.clearInterval(id)},[]);
 const stats=useMemo(()=>{const s:Record<string,number>={};feed.forEach(x=>s[x.type]=(s[x.type]||0)+1);return s},[feed]);
 const notify=(x:string)=>{setToast(x);window.setTimeout(()=>setToast(""),2200)};
 const submit=async()=>{if(!selected||busy)return;const type=selected[1];if(["note","joke","song"].includes(type)&&!content.trim()){notify("Give it a little something first 💌");return}setBusy(true);try{const r=await fetch("/api/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,sender:sender||"Anonymous",content:content||selected[3],mood})});if(!r.ok)throw new Error();setContent("");setSender("");setSelected(null);await load();notify("Left in Noor's world 🌻")}catch{notify("The little mailbox tripped over itself. Try again.")}finally{setBusy(false)}};
 return <main className={night?"world night":"world"}>
  <header className="topbar"><div className="brand"><span className="brand-flower">🌻</span><div><b>Noor World</b><small>her little corner of the internet</small></div></div><button className="icon-btn" onClick={()=>setNight(!night)}>{night?"☀️":"🌙"}</button></header>
  <section className="hero"><div className="hero-copy"><span className="eyebrow">a tiny internet made of people</span><h1>Welcome to<br/><em>Noor's world.</em></h1><p>Flowers grow here. Friends leave little things. Some days are silly, some are quiet. Nothing here asks her to be anything.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab("send")}>Leave something 🌷</button><button className="soft" onClick={()=>setTab("play")}>Explore ✨</button></div></div><div className="sky"><span className="sun">☀️</span><span className="cloud c1">☁️</span><span className="cloud c2">☁️</span><span className="butterfly">🦋</span><div className="mountain m1"/><div className="mountain m2"/><div className="grass"/>{["🌻","🌷","🌼","🌻"].map((x,i)=><span className={"flower f"+(i+1)} key={i}>{x}</span>)}<span className="bee">🐝</span></div></section>
  <section className="little-card"><div><span className="eyebrow">people who thought of her</span><h2>{feed.length} little things have been left here.</h2><p>This number grows whenever somebody stops by and leaves a little piece of kindness.</p></div><div className="mini-stats"><span>🌷 {stats.flower||0}</span><span>🫂 {stats.hug||0}</span><span>💌 {stats.note||0}</span><span>😂 {stats.joke||0}</span></div></section>
  {tab==="home"&&<><section className="section"><div className="section-head"><div><span className="eyebrow">the little inbox</span><h2>People left something.</h2></div><button className="text-btn" onClick={()=>setTab("send")}>leave yours →</button></div><div className="feed">{feed.length===0?<div className="empty">The garden is waiting for its first little thing. 🌻</div>:feed.map(x=><button className="feed-card" key={x.id} onClick={()=>setSelected([gifts.find(g=>g[1]===x.type)?.[0]||"🌻",x.type,labels[x.type]||"left something",x.content])}><span className="feed-icon">{gifts.find(g=>g[1]===x.type)?.[0]||"🌻"}</span><span><b>{x.sender_name} <small>{labels[x.type]||"left something"}</small></b><p>{x.content||"No words needed. 🤍"}</p><time>{new Date(x.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</time></span><i>›</i></button>)}</div></section>
  <section className="section"><div className="section-head"><div><span className="eyebrow">made for friends</span><h2>Do something silly.</h2></div></div><div className="grid">{[["🧠","Know Noor","A tiny quiz for people who think they know her."],["🎯","Daily question","One extremely important question."],["😂","Make Me Laugh","Friends compete to make Noor laugh."],["🌻","Build the flower","Everyone adds a petal."],["🐻","Pet corner","Feed, dress and annoy tiny pets."],["🏆","Noor Awards","Nominate her for something ridiculous."]].map((g,i)=><button className="feature" key={i} onClick={()=>notify("✨ "+g[1]+" is joining the world.")}><span>{g[0]}</span><b>{g[1]}</b><p>{g[2]}</p></button>)}</div></section></>}
  {tab==="play"&&<section className="section"><div className="section-head"><div><span className="eyebrow">playground</span><h2>Important nonsense.</h2><p>Games, quizzes, polls and friend challenges live here.</p></div></div><div className="grid">{[["👆","Tap 20 Times","Tap until dignity leaves the room."],["⚡","Reaction Test","Let's measure human reflexes."],["🔢","Guess My Number","1 to 10. No suspicious cheating."],["🧠","Remember This","Your brain has been summoned."],["😈","Annoy Me Back","An important scientific experiment."],["🏆","Noor Awards","Give her a completely unnecessary award."],["🗳️","Daily Poll","Vote on something deeply important."],["📸","Meanwhile","Leave a tiny snapshot of your day."],["🔒","Open When","Make an envelope for future Noor."]].map((g,i)=><button className="feature" key={i} onClick={()=>notify("✨ "+g[1]+" is part of the real world build.")}><span>{g[0]}</span><b>{g[1]}</b><p>{g[2]}</p></button>)}</div></section>}
  {tab==="send"&&<section className="section"><div className="section-head"><div><span className="eyebrow">leave something for Noor</span><h2>Pick a little thing.</h2><p>No reply required. Just leave it here.</p></div></div><div className="send-grid">{gifts.map(g=><button className="send-card" key={g[1]} onClick={()=>setSelected(g)}><span>{g[0]}</span><b>{g[2]}</b><p>{g[3]}</p><strong>leave it →</strong></button>)}</div></section>}
  <section className="garden-card"><div><span className="eyebrow">noor's garden</span><h2>It grows when people care.</h2><p>Every flower, hug, note and ridiculous little gift becomes part of this world.</p></div><div className="garden-art">🌻 🌷 🌼 🪻 🌻<br/>🦋 🌸 🫂 🌷 🐝</div></section>
  <nav className="bottom"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}>🌻<small>home</small></button><button className={tab==="play"?"active":""} onClick={()=>setTab("play")}>🎮<small>play</small></button><button className={tab==="send"?"active":""} onClick={()=>setTab("send")}>💌<small>send</small></button></nav>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal send-modal" onClick={e=>e.stopPropagation()}><span>{selected[0]}</span><h3>{selected[2]}</h3>{selected[1]==="flower"&&<div className="flower-picker">{["🌻","🌷","🌹","🌸","🌼","🪻","🌺"].map(x=><button key={x} onClick={()=>setContent(x)} className={content===x?"picked":""}>{x}</button>)}</div>}<input value={sender} onChange={e=>setSender(e.target.value)} placeholder="Your name (or leave blank for Anonymous)"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder={selected[1]==="flower"?"Add a tiny note about the flower...":"Write something small and real..."} maxLength={1000}/><select value={mood} onChange={e=>setMood(e.target.value)}><option value="just-because">🌻 Just because</option><option value="happy">☀️ For a good day</option><option value="laugh">😂 To make you laugh</option><option value="hug">🫂 Because you need a hug</option><option value="difficult">🌧️ For a difficult day</option></select><button className="primary full" disabled={busy} onClick={submit}>{busy?"leaving it...":"Leave it in the garden 🌷"}</button></div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main>
}