"use client";
import {useState} from "react";

const things=[["🌷","Send a flower","Build a tiny flower and leave it in her garden."],["🫂","Send a hug","No words required. Just show up."],["💌","Leave a note","A tiny message, anonymous or signed."],["😂","Make her laugh","Jokes, cursed stories and terrible ideas."],["☕","Send coffee","Emotionally responsible caffeine delivery."],["🎵","Leave a song","Attach a song to a tiny moment."],["🏆","Nominate her","Give Noor an award she absolutely did not ask for."],["✨","Leave a sparkle","For no reason. The best reason."]];
const games=[["🧠","Know Noor","See who actually knows her."],["🎯","Daily question","One extremely important question per day."],["😂","Make Me Laugh","Friends compete to make Noor laugh."],["🌻","Build the flower","Everyone adds a petal."],["🐻","Pet corner","Feed, dress and annoy the tiny pets."]];
export default function NoorWorld(){const [night,setNight]=useState(false);const [tab,setTab]=useState<"home"|"play"|"send">("home");const [sent,setSent]=useState(0);const [toast,setToast]=useState<string|null>(null);const [open,setOpen]=useState<string|null>(null);
const notify=(s:string)=>{setToast(s);setSent(v=>v+1);setTimeout(()=>setToast(null),2200)};
return <main className={night?"world night":"world"}>
<header className="topbar"><div className="brand"><span className="brand-flower">🌻</span><div><b>Noor World</b><small>her little corner of the internet</small></div></div><button className="icon-btn" onClick={()=>setNight(!night)}>{night?"☀️":"🌙"}</button></header>
<section className="hero"><div className="hero-copy"><span className="eyebrow">A tiny internet made with love</span><h1>Welcome to<br/><em>Noor's world.</em></h1><p>Flowers grow here. Friends leave little things. Some days are silly. Some days are quiet. There is no pressure to be anything.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab("send")}>Leave something 🌷</button><button className="soft" onClick={()=>setTab("play")}>Explore the world ✨</button></div></div><div className="sky"><span className="sun">☀️</span><span className="cloud c1">☁️</span><span className="cloud c2">☁️</span><span className="butterfly">🦋</span><div className="mountain m1"></div><div className="mountain m2"></div><div className="grass"></div><div className="flower f1">🌻</div><div className="flower f2">🌷</div><div className="flower f3">🌼</div><div className="flower f4">🌻</div><div className="bee">🐝</div></div></section>
<section className="little-card"><div><span className="eyebrow">Today</span><h2>7 little things were left here.</h2><p>From 4 people who thought of Noor today.</p></div><div className="mini-stats"><span>🌷 3</span><span>🫂 2</span><span>💌 1</span><span>😂 1</span></div></section>
{tab==="home"&&<><section className="section"><div className="section-head"><div><span className="eyebrow">People who care</span><h2>Little things, left here.</h2></div><button className="text-btn" onClick={()=>setTab("send")}>send something →</button></div><div className="feed">{[["🌷","Riya","left a sunflower","Just because. 🌻"],["🫂","Aanya","sent a bear hug","No explanation necessary."],["😂","Someone","tried to make Noor laugh","Why did the tomato blush? It saw the salad dressing."],["🎵","Mehak","left a song","For your evening walk."]].map((x,i)=><button className="feed-card" key={i} onClick={()=>setOpen(x[3])}><span className="feed-icon">{x[0]}</span><span><b>{x[1]} <small>{x[2]}</small></b><p>{x[3]}</p><time>today · {i+2}:1{i}</time></span><i>›</i></button>)}</div></section><section className="section"><div className="section-head"><div><span className="eyebrow">Made for friends</span><h2>Do something silly.</h2></div></div><div className="grid">{games.map((g,i)=><button className="feature" key={i} onClick={()=>setTab("play")}><span>{g[0]}</span><b>{g[1]}</b><p>{g[2]}</p></button>)}</div></section></>}
{tab==="play"&&<section className="section"><div className="section-head"><div><span className="eyebrow">Playground</span><h2>Important nonsense.</h2><p>Because apparently websites need games now.</p></div></div><div className="grid">{games.concat([["🏅","Noor Awards","Nominate her for something ridiculous."],["📸","Meanwhile","Leave a tiny snapshot of your day."],["🔮","Secret","Leave something mysterious."]]).map((g,i)=><button className="feature" key={i} onClick={()=>notify(g[1]+" is coming to life ✨")}><span>{g[0]}</span><b>{g[1]}</b><p>{g[2]}</p></button>)}</div></section>}
{tab==="send"&&<section className="section"><div className="section-head"><div><span className="eyebrow">Leave something for Noor</span><h2>Pick a little thing.</h2><p>No reply required. Just leave it here.</p></div></div><div className="send-grid">{things.map((t,i)=><button className="send-card" key={i} onClick={()=>notify(t[1]+" added to the garden 🌻")}><span>{t[0]}</span><b>{t[1]}</b><p>{t[2]}</p><strong>leave it →</strong></button>)}</div></section>}
<section className="garden-card"><div><span className="eyebrow">Noor's Garden</span><h2>It grows when people care.</h2><p>Every flower, hug, note and ridiculous little gift becomes part of the world.</p></div><div className="garden-art">🌻 🌷 🌼 🪻 🌻<br/>🦋 🌸 🫂 🌷 🐝</div></section>
<nav className="bottom"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}>🌻<small>home</small></button><button className={tab==="play"?"active":""} onClick={()=>setTab("play")}>🎮<small>play</small></button><button className={tab==="send"?"active":""} onClick={()=>setTab("send")}>💌<small>send</small></button></nav>
{toast&&<div className="toast">{toast}</div>}{open&&<div className="modal-backdrop" onClick={()=>setOpen(null)}><div className="modal" onClick={e=>e.stopPropagation()}><span>🌻</span><h3>A little thing was left for Noor.</h3><p>{open}</p><button className="primary" onClick={()=>setOpen(null)}>keep it 🌷</button></div></div>}
</main>}